name    'zordrak-puppet'
version '2.1.2'
source 'git://github.com/zordrak/puppet-puppet'
author 'zordrak'
license 'GPLv3+'
summary 'Puppet agent and server configuration'
description 'Module for installing the Puppet agent and Puppet server'
project_page 'http://github.com/zordrak/foreman-installer'

dependency 'theforeman/concat_native', '>= 1.3.0'
dependency 'theforeman/foreman', '>= 1.3.0'
dependency 'theforeman/git', '>= 1.3.0'
dependency 'puppetlabs/apache', '>= 1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>= 2.0.0'
